import { Achievement } from "../types";

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_hire",
    title: "First Hire",
    description: "Get hired for the first time",
    icon: "🤝",
    progress: 0,
    isCompleted: false,
    xpReward: 50,
  },
  {
    id: "hot_streak",
    title: "Hot Streak",
    description: "Maintain a 7-day login streak",
    icon: "🔥",
    progress: 0,
    isCompleted: false,
    xpReward: 100,
  },
  {
    id: "tech_polyglot",
    title: "Tech Polyglot",
    description: "Add 5+ technologies to your stack",
    icon: "🌐",
    progress: 0,
    isCompleted: false,
    xpReward: 75,
  },
  {
    id: "elite_status",
    title: "Elite Status",
    description: "Reach Senior level",
    icon: "⭐",
    progress: 0,
    isCompleted: false,
    xpReward: 200,
  },
  {
    id: "legendary_dev",
    title: "Legendary Dev",
    description: "Reach Legendary level",
    icon: "👑",
    progress: 0,
    isCompleted: false,
    xpReward: 500,
  },
  {
    id: "popular_pick",
    title: "Popular Pick",
    description: "Get hired 10 times",
    icon: "🏅",
    progress: 0,
    isCompleted: false,
    xpReward: 150,
  },
  {
    id: "speedrun",
    title: "Speedrun",
    description: "Create a card in under 60 seconds",
    icon: "⚡",
    progress: 0,
    isCompleted: false,
    xpReward: 25,
  },
  {
    id: "full_stack",
    title: "Full Stack",
    description: "Have both Frontend and Backend in tech stack",
    icon: "🥞",
    progress: 0,
    isCompleted: false,
    xpReward: 60,
  },
];
